### ISSUE TITLE
Machine GUIs don't work on server

### ISSUE THREAD

**Issue by sblectric** [setycz/AnotherDustsMod#15]
When you attempt to open the gui of a machine on a server, the server crashes and you're unable to remove the block.

Crash report: http://pastebin.com/AUASF1k0

**Comment by setycz** [comment]
I'll check that and let you know. Thank you for your feedback.

**Comment by setycz** [comment]
The issue is fixed, download 1.4.1 version from http://minecraft.curseforge.com/projects/another-dusts/files/2282865 . Than you for your feedback! ;]
