### ISSUE TITLE
Multiple entries with same key:

### ISSUE THREAD

**Issue by ghost** [setycz/AnotherDustsMod#16]
crash-log see: http://paste.ee/p/KXjSg

Can you fix that.
I Iike your mod a lot

**Comment by setycz** [comment]
I'll check that. Thanks for the report.;]

**Comment by setycz** [comment]
I checked that but, unfortunately, I cannot fixed that. The bug is in Afterhours mod, they used my source code without proper changes and that's why the conflict appeared. I see you already contacted them as well: https://github.com/kyau/afterhours/issues/1 ;]. I'll help them to solve the issue.
