### ISSUE TITLE
1.9-2.0 crashes dedicated forge server 1.9 build 1865 on startup

### ISSUE THREAD

**Issue by kreezxil** [setycz/AnotherDustsMod#18]
Issue: anotherdusts-1.9-2.0 crashes dedicated forge server 1.9 build 1865 on startup

crash report:
https://gist.github.com/57a0d53d3f23065d352688e953ba925a

fml server latest:
https://gist.github.com/103a44b5ab3a96943f4e2e04790b5734

**Comment by kreezxil** [comment]
Would like to point at that build version 1.9-1.4.1 doesn't crash the server on startup.

**Comment by setycz** [comment]
Hi. Thank you for the bug report. I've updated the mod to Forge 1865. Check version 2.0.1.
